/*
 * Banshee - 2014 
 *  
 * Incubamatic 3000 DB
 */


CREATE TABLE IF NOT EXISTS Temp (
   ID         INTEGER PRIMARY KEY AUTOINCREMENT,
   EVENT_TIME DATETIME  DEFAULT  CURRENT_TIMESTAMP,
   SENSOR     INTEGER,
   VALUE      REAL
);

CREATE TABLE IF NOT EXISTS Hum (
   ID         INTEGER PRIMARY KEY AUTOINCREMENT,
   EVENT_TIME DATETIME  DEFAULT  CURRENT_TIMESTAMP,
   SENSOR     INTEGER,
   VALUE      REAL
);
